# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0002_auto_20170828_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-pub_date',)},
        ),
    ]
