# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_blog', '0005_auto_20170901_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_rating',
        ),
        migrations.AddField(
            model_name='article',
            name='article_rating',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
