# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0007_auto_20170912_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
    ]
