# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_blog', '0008_auto_20170912_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='article_rating',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
