# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0009_auto_20170912_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_rating',
        ),
    ]
